name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  ## Allow running workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      verbose:
        description: "Output more information when triggered manually"
        required: false
        default: ""

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.events.input.verbose }}

jobs:
  test:
    name: cargo test (${{ matrix.directory }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: substrate/frame
            exclude: '^(contracts|pallet-revive-fixtures|pallet-contracts-fixtures-common)$'
          - directory: substrate/primitives
            exclude: '^sp-state-machine-fuzz$'
          - directory: substrate/client
            exclude: '^THIS_PATTERN_MATCHES_NOTHING$'
    env:
      RUST_BACKTRACE: full
      SKIP_PALLET_REVIVE_FIXTURES: 1
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4
        
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: cargo-cache
          cache-on-failure: true

      - name: Test ${{ matrix.directory }}
        run: |
          PACKAGES=$(find ${{ matrix.directory }} -name Cargo.toml -exec yq -r '.package.name' {} \; 2>/dev/null \
            | grep -vE '${{ matrix.exclude }}' \
            | while read crate; do echo "-p $crate"; done \
            | tr '\n' ' ')
          cargo test $PACKAGES
